/* Generated by Yosys 0.61+56 (git sha1 a6fc69552, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "vend.v:1.1-97.10" *)
module vending_machine(coin, clock, reset, newspaper);
  (* src = "vend.v:2.12-2.16" *)
  input [1:0] coin;
  wire [1:0] coin;
  (* src = "vend.v:3.7-3.12" *)
  input clock;
  wire clock;
  (* src = "vend.v:4.7-4.12" *)
  input reset;
  wire reset;
  (* src = "vend.v:5.14-5.23" *)
  output newspaper;
  wire newspaper;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  (* src = "vend.v:2.12-2.16" *)
  wire _29_;
  (* src = "vend.v:2.12-2.16" *)
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  (* src = "vend.v:4.7-4.12" *)
  wire _39_;
  (* onehot = 32'd1 *)
  wire [3:0] PRESENT_STATE;
  (* nosync = 32'd1 *)
  (* src = "vend.v:20.11-20.25" *)
  wire [1:0] \fsm$func$vend.v:87$2.fsm_NEXT_STATE ;
  (* nosync = 32'd1 *)
  (* src = "vend.v:18.12-18.29" *)
  wire [1:0] \fsm$func$vend.v:87$2.fsm_PRESENT_STATE ;
  (* nosync = 32'd1 *)
  (* src = "vend.v:17.12-17.20" *)
  wire [1:0] \fsm$func$vend.v:87$2.fsm_coin ;
  (* nosync = 32'd1 *)
  (* src = "vend.v:19.6-19.19" *)
  wire \fsm$func$vend.v:87$2.fsm_newspaper ;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _40_ (
    .A(_30_),
    .SLEEP(_29_),
    .X(_31_)
  );
  sky130_fd_sc_hd__nor3b_1 _41_ (
    .A(_39_),
    .B(_29_),
    .C_N(_30_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _42_ (
    .A(_29_),
    .SLEEP(_30_),
    .X(_33_)
  );
  sky130_fd_sc_hd__nor3b_1 _43_ (
    .A(_39_),
    .B(_30_),
    .C_N(_29_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nor2_1 _44_ (
    .A(_23_),
    .B(_22_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__a21oi_1 _45_ (
    .A1(_22_),
    .A2(_34_),
    .B1(_32_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__nor2_1 _46_ (
    .A(_35_),
    .B(_36_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nor3_1 _47_ (
    .A(_39_),
    .B(_31_),
    .C(_33_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__a22o_1 _48_ (
    .A1(_21_),
    .A2(_34_),
    .B1(_37_),
    .B2(_23_),
    .X(_27_)
  );
  sky130_fd_sc_hd__a22o_1 _49_ (
    .A1(_21_),
    .A2(_32_),
    .B1(_34_),
    .B2(_23_),
    .X(_38_)
  );
  sky130_fd_sc_hd__a21o_1 _50_ (
    .A1(_22_),
    .A2(_37_),
    .B1(_38_),
    .X(_26_)
  );
  sky130_fd_sc_hd__a211o_1 _51_ (
    .A1(_21_),
    .A2(_37_),
    .B1(_24_),
    .C1(_39_),
    .X(_25_)
  );
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(clock),
    .D(_00_),
    .Q(PRESENT_STATE[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(clock),
    .D(_01_),
    .Q(PRESENT_STATE[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clock),
    .D(_02_),
    .Q(PRESENT_STATE[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clock),
    .D(_03_),
    .Q(PRESENT_STATE[3])
  );
  assign \fsm$func$vend.v:87$2.fsm_NEXT_STATE  = 2'hx;
  assign \fsm$func$vend.v:87$2.fsm_PRESENT_STATE  = 2'hx;
  assign \fsm$func$vend.v:87$2.fsm_coin  = 2'hx;
  assign \fsm$func$vend.v:87$2.fsm_newspaper  = 1'hx;
  assign newspaper = PRESENT_STATE[3];
  assign _39_ = reset;
  assign _23_ = PRESENT_STATE[2];
  assign _22_ = PRESENT_STATE[1];
  assign _29_ = coin[0];
  assign _30_ = coin[1];
  assign _03_ = _28_;
  assign _21_ = PRESENT_STATE[0];
  assign _02_ = _27_;
  assign _01_ = _26_;
  assign _24_ = PRESENT_STATE[3];
  assign _00_ = _25_;
endmodule
