/* Generated by Yosys 0.61+56 (git sha1 a6fc69552, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "4_bit_gray_encoder.v:1.1-10.10" *)
module gray_encoder(bin_in, gray_out);
  (* src = "4_bit_gray_encoder.v:2.12-2.18" *)
  input [3:0] bin_in;
  wire [3:0] bin_in;
  (* src = "4_bit_gray_encoder.v:3.13-3.21" *)
  output [3:0] gray_out;
  wire [3:0] gray_out;
  (* src = "4_bit_gray_encoder.v:2.12-2.18" *)
  wire _0_;
  (* src = "4_bit_gray_encoder.v:2.12-2.18" *)
  wire _1_;
  (* src = "4_bit_gray_encoder.v:2.12-2.18" *)
  wire _2_;
  (* src = "4_bit_gray_encoder.v:2.12-2.18" *)
  wire _3_;
  (* src = "4_bit_gray_encoder.v:3.13-3.21" *)
  wire _4_;
  (* src = "4_bit_gray_encoder.v:3.13-3.21" *)
  wire _5_;
  (* src = "4_bit_gray_encoder.v:3.13-3.21" *)
  wire _6_;
  sky130_fd_sc_hd__xor2_1 _7_ (
    .A(_2_),
    .B(_3_),
    .X(_6_)
  );
  sky130_fd_sc_hd__xor2_1 _8_ (
    .A(_2_),
    .B(_1_),
    .X(_5_)
  );
  sky130_fd_sc_hd__xor2_1 _9_ (
    .A(_1_),
    .B(_0_),
    .X(_4_)
  );
  assign gray_out[3] = bin_in[3];
  assign _2_ = bin_in[2];
  assign _3_ = bin_in[3];
  assign gray_out[2] = _6_;
  assign _1_ = bin_in[1];
  assign gray_out[1] = _5_;
  assign _0_ = bin_in[0];
  assign gray_out[0] = _4_;
endmodule
